# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalender', '0002_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=50),
        ),
    ]
