# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalender', '0003_auto_20170207_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(default='yyyy-mm-dd', max_length=11),
        ),
    ]
